cuda_visible_devices: 0

data_path: ../data/ml-1m.txt

dataset:
  max_length: 50
  mlm_probability: 0.2
  force_last_item_masking_prob: 0

dataloader:
  batch_size: 128
  test_batch_size: 256
  num_workers: 8
  validation_size: 10000

model: BERT4Rec
model_params:
  vocab_size: 2
  max_position_embeddings: 200
  hidden_size: 64
  num_hidden_layers: 2
  num_attention_heads: 2
  intermediate_size: 256

seqrec_module:
  lr: 0.001
  predict_top_k: 10  # this value is used for validation
  filter_seen: True

trainer_params:
  max_epochs: 200

patience: 20
sampled_metrics: False
top_k_metrics: [1, 10, 100]
