cuda_visible_devices: 0

data_path: ../data/ml-1m.txt

dataset:
  max_length: 50
  # num_negatives: 
  full_negative_sampling: True

dataloader:
  batch_size: 128
  test_batch_size: 256
  num_workers: 8
  validation_size: 10000

model: GPT4Rec
model_params:
  vocab_size: 2
  n_positions: 200
  n_embd: 64
  n_layer: 2
  n_head: 1

seqrec_module:
  lr: 0.001
  predict_top_k: 10  # this value is used for validation
  filter_seen: True
  # loss: bce

trainer_params:
  max_epochs: 100

patience: 10
sampled_metrics: False
top_k_metrics: [10, 50, 100]