cuda_visible_devices: 0

data_path: ../data/ml-1m.txt

dataset:
  max_length: 50
  # num_negatives:
  full_negative_sampling: False

dataloader:
  batch_size: 128
  test_batch_size: 256
  num_workers: 8
  validation_size: 10000

model: RNN
model_params:
  input_size: 64
  hidden_size: 64
  num_layers: 1
  dropout: 0.1

seqrec_module:
  lr: 0.001
  predict_top_k: 10  # this value is used for validation
  filter_seen: True

trainer_params:
  max_epochs: 100

patience: 10
sampled_metrics: False
top_k_metrics: [10, 100]